#!/usr/bin/env bash
# bash script that displays "To infinity and beyond" indefinetly
# requirement: in between each iteration of the loop and a sleep 2

while true
do
	echo "To infinity and beyond"
	sleep 2
done
