#!/usr/bin/env bash
# bash script displays "bad luck" at loop iteration 4
# and "good luck" at loop iteration 8 and "Best School"
# for the rest

export i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i += 1))

done
