#!/usr/bin/env bash
# bash script that configures an ubuntu server with localhost reslves to
# 127:0:0:2 and also fecabook.com resolves to 8:8:8:8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8:8:8:8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
